version: '3.8'
services:
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      - DB_HOST_NAME=postgres
      
  postgres:
    image: postgres:alpine3.16
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - '5432:5432'
    volumes: 
      - ./db:/var/lib/postgresql/data
  
volumes:
  db:
    driver: local